[package]
name = "gem-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.74", features = ["extra-traits", "full", "fold"] }
quote = "1.0.9"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
